-- 005_openrouter_embed_1024.sql - migrate embeddings to OpenRouter liquid/lfm-2.5-embedding-350m (1024-dim).
--
-- OpenRouter.s lfm-2.5-embedding-350m emits 1024-dim vectors while this DB was created for
-- NVIDIA Nemotron-3 (2048-dim). pgvector cannot cast a populated 2048-dim column
-- down to 1024, so this migration:
--   1. drops the old halfvec(2048) HNSW index,
--   2. makes the column nullable and NULLs existing embeddings (regenerated by
--      scripts/reembed_openrouter.py; content/allowed_roles are preserved),
--   3. alters the column type to vector(1024),
--   4. creates a normal (non-halfvec) HNSW index on the 1024-dim column.
--
-- Guarded + idempotent: only acts when the column is currently vector(2048), so
-- re-running on startup is a no-op once migrated. Fresh DBs created by
-- database.py SCHEMA_SQL already use vector(1024) and are left untouched.
-- embeddings stay nullable after migration until the re-embed script fills them.

DO $$
DECLARE
  dim integer;
BEGIN
  SELECT a.atttypmod INTO dim
  FROM pg_attribute AS a
  WHERE a.attrelid = 'public.chunks'::regclass
    AND a.attname = 'embedding'
    AND NOT a.attisdropped;

  IF dim = 2048 THEN
    DROP INDEX IF EXISTS public.chunks_embedding_hnsw_idx;

    ALTER TABLE public.chunks ALTER COLUMN embedding DROP NOT NULL;
    UPDATE public.chunks SET embedding = NULL;

    ALTER TABLE public.chunks ALTER COLUMN embedding TYPE vector(1024);

    CREATE INDEX IF NOT EXISTS chunks_embedding_hnsw_idx
      ON public.chunks USING hnsw (embedding vector_cosine_ops);

  ELSIF dim <> 1024 THEN
    RAISE EXCEPTION
      'Unsupported chunks.embedding dimension: % (expected 1024)', dim;
  END IF;
END
$$;
