// constants/testIds/sentry.js - central test IDs for Sentry RAG
export const LANDING = {
  navSkipToConsole: 'landing-nav-skip-to-console-link',
  heroPrimaryCta: 'landing-hero-primary-cta-button',
  heroSecondaryCta: 'landing-hero-secondary-cta-button',
  featureGrounded: 'landing-feature-grounded-panel',
  featureAccess: 'landing-feature-access-panel',
  featureAdmin: 'landing-feature-admin-panel',
  featureAudit: 'landing-feature-audit-panel',
  finalCtaButton: 'landing-final-cta-button',
  finalCtaRegister: 'landing-final-cta-register-link',
};

export const AUTH = {
  emailInput: 'auth-email-input',
  passwordInput: 'auth-password-input',
  confirmPasswordInput: 'auth-confirm-password-input',
  submitButton: 'auth-submit-button',
  switchToRegister: 'auth-switch-to-register-link',
  switchToLogin: 'auth-switch-to-login-link',
  errorMessage: 'auth-error-message',
  pendingBackToLogin: 'auth-pending-back-to-login-button',
  changePasswordCurrent: 'auth-change-password-current-input',
  changePasswordNew: 'auth-change-password-new-input',
  changePasswordConfirm: 'auth-change-password-confirm-input',
  changePasswordSubmit: 'auth-change-password-submit-button',
};

export const CHAT = {
  sidebar: 'chat-sidebar',
  newConversationButton: 'chat-new-conversation-button',
  conversationItem: 'chat-conversation-item',
  conversationItemDelete: 'chat-conversation-item-delete',
  topBarRoleBadge: 'chat-top-bar-role-badge',
  topBarUserEmail: 'chat-top-bar-user-email',
  logoutButton: 'chat-logout-button',
  goToAdminButton: 'chat-go-to-admin-button',
  messageInput: 'chat-message-input',
  sendButton: 'chat-send-button',
  messageBubbleUser: 'chat-message-bubble-user',
  messageBubbleAssistant: 'chat-message-bubble-assistant',
  citationChip: 'chat-message-citation-chip',
  retrievalToggle: 'chat-message-retrieval-details-toggle',
  retrievedCount: 'chat-message-retrieved-count',
  blockedCount: 'chat-message-blocked-count',
  retrievalRetrievedRow: 'chat-message-retrieval-retrieved-row',
  retrievalBlockedRow: 'chat-message-retrieval-blocked-row',
  emptyState: 'chat-empty-state',
};

export const ADMIN = {
  usersTab: 'admin-tab-users',
  documentsTab: 'admin-tab-documents',
  pendingUserRow: 'admin-pending-user-row',
  pendingUserRoleSelect: 'admin-pending-user-role-select',
  pendingUserApproveButton: 'admin-pending-user-approve-button',
  approvedUserRow: 'admin-approved-user-row',
  approvedUserRoleSelect: 'admin-approved-user-role-select',
  docUploadDropzone: 'admin-doc-upload-dropzone',
  docUploadFileInput: 'admin-doc-upload-file-input',
  docUploadTitleInput: 'admin-doc-upload-title-input',
  docUploadRoleCheckbox: 'admin-doc-upload-role-checkbox',
  docUploadSubmit: 'admin-doc-upload-submit-button',
  docListRow: 'admin-doc-list-row',
  docListEditButton: 'admin-doc-list-edit-button',
  docListDeleteButton: 'admin-doc-list-delete-button',
  docEditRoleCheckbox: 'admin-doc-edit-role-checkbox',
  docEditSave: 'admin-doc-edit-save-button',
  backToChatButton: 'admin-back-to-chat-button',
};
